services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: ["sh", "/usr/local/bin/start-app"]

  vite:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: ["sh", "/usr/local/bin/start-vite"]
